version: "3.9"
services:
  pg:
    image: postgres:16
    container_name: shareit-pg
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: shareit
      POSTGRES_PASSWORD: shareit
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shareit -d shareit"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata: