-- USERS
CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name  VARCHAR(255) NOT NULL,
email VARCHAR(512) NOT NULL,
CONSTRAINT uq_users_email UNIQUE (email)
);

-- REQUEST
CREATE TABLE IF NOT EXISTS item_requests (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
description  VARCHAR(1000) NOT NULL,
requester_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_item_requests_created  ON item_requests (created DESC);
CREATE INDEX IF NOT EXISTS ix_item_requests_requester ON item_requests (requester_id);

-- ITEMS
CREATE TABLE IF NOT EXISTS items (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name        VARCHAR(255) NOT NULL,
description VARCHAR(1000),
available   BOOLEAN NOT NULL,
owner_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
request_id  BIGINT REFERENCES requests(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_items_owner   ON items(owner_id);
CREATE INDEX IF NOT EXISTS ix_items_request ON items(request_id);

-- BOOKINGS
CREATE TABLE IF NOT EXISTS bookings (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
end_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
item_id    BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
booker_id  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
status     VARCHAR(12) NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_bookings_item_end   ON bookings (item_id, end_date DESC);
CREATE INDEX IF NOT EXISTS ix_bookings_item_start ON bookings (item_id, start_date ASC);
CREATE INDEX IF NOT EXISTS ix_bookings_item_status_start ON bookings (item_id, status, start_date);
CREATE INDEX IF NOT EXISTS ix_bookings_item_status_end   ON bookings (item_id, status, end_date);

-- COMMENTS
CREATE TABLE IF NOT EXISTS comments (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
text      VARCHAR(1000) NOT NULL,
created   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
item_id   BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_comments_item   ON comments (item_id);
CREATE INDEX IF NOT EXISTS ix_comments_author ON comments (author_id);
